### ISSUE TITLE
Limit line length

### ISSUE THREAD

**Issue by nventuro** [ZeppelinSolutions/code-style#3]
To comply with the [Solidity style guide](https://solidity.readthedocs.io/en/develop/style-guide.html#maximum-line-length), we should add a rule to limit the maximum line length to 79 characters (note that solium doesn't yet support such a rule).

I would also drop the `arg-overflow` rule, since this one tackles the same problem.

**Comment by elopio** [comment]
I proposed a simple implementation of long-lines to solium: https://github.com/duaraghav8/Solium/pull/199

**Comment by elopio** [comment]
I like it very much to use short lines. I have a big monitor, but I increase the size of the font size a lot, so using two byobu splits side by side, I have just enough room for 80 characters in a line. Also, I usually read code on my phone, and on portrait mode short lines ok to read. Long lines not so much. And finally, the github diff is presented in two colums, so it's easier to read the diff and leave comments in a line if those lines are short.

Those are *my* personal reasons. But this rule is mentioned on the [solidity style guide](http://solidity.readthedocs.io/en/latest/style-guide.html#maximum-line-length). My strong opinion goes to follow that guide as close as possible, only deviating if there's a very good reason.

**Comment by frangio** [comment]
+1 to following this rule.
